account/urls.py
from django.conf.urls import url
from . import views

app_name = 'account'
urlpatterns = [
    url(r'^mypage/$', views.MyPageView.as_view(), name='mypage'),
    url(r'^create/$', views.CreateUserView.as_view(), name='create'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tenpo.urls')),
    url(r'^account/', include('account.urls')),
]

tenpo/urls.py
from django.conf.urls import url
from . import views

app_name = 'tenpo'
urlpatterns = [
    url(r'^$', views.TopPageView.as_view(), name='index'),
    url(r'^tenpo/$', views.TenpoListView.as_view(), name='tenpo'),
    url(r'^rireki/$', views.RirekiListView.as_view(), name='rireki'),
    url(r'^favorite/$', views.FavoriteListView.as_view(), name='favorite'),
]

account/models.py
from django.db import models

# Create your models here.

tenpo/models.py
from django.db import models
from django.contrib.auth.models import User

class Tenpo(models.Model):
	tenpo_name = models.CharField(default='tenpo',max_length=200)
	tenpo_genre = models.CharField(default='genre',max_length=200)
	tenpo_address = models.CharField(default='address',max_length=500)
	tenpo_phone_number = models.CharField(default='0660123456',max_length=500)
	tenpo_pr_message = models.CharField(default='message',max_length=1000)

	def __str__(self):
		return self.tenpo_name

class Rireki(models.Model):
	rireki_tenpo = models.ForeignKey(Tenpo,on_delete=models.CASCADE)
	rireki_user = models.ForeignKey(User,on_delete=models.CASCADE)

	def __str__(self):
		return self.rireki_tenpo.tenpo_name

class Favorite(models.Model):
	favorite_tenpo = models.ForeignKey(Tenpo,on_delete=models.CASCADE)
	favorite_user = models.ForeignKey(User,on_delete=models.CASCADE)

	def __str__(self):
		return self.favorite_tenpo.tenpo_name

def genreTable():
	return (
		(1,'飲食店'),
		(2,'ショッピング'),
		(3,'ヘルス'),
		(4,'ホテル'),
		(5,'美容'),
		(6,'その他'),
	)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "username", "password1", "password2",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'ユーザ名'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'パスワード'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'パスワード（確認）'

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'ユーザ名'

        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['placeholder'] = 'パスワード'

account/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from .forms import RegisterForm, LoginForm

class MyPageView(LoginRequiredMixin, generic.TemplateView):
    template_name = "account/info.html"

class CreateUserView(generic.CreateView):
    template_name = 'account/create.html'
    form_class = RegisterForm
    success_url = reverse_lazy('tenpo:index')

def login(request):
    context = {
        'template_name': 'account/login.html',
        'authentication_form': LoginForm
    }
    return auth_views.login(request, **context)

def logout(request):
    context = {
        'template_name': 'tenpo/index.html',
    }
    return auth_views.logout(request, **context)

tenpo/views.py
from django.views.generic import TemplateView,ListView
from .models import Tenpo,Rireki,Favorite

class TopPageView(TemplateView):
    template_name = 'tenpo/index.html'

class TenpoListView(ListView):
	model = Tenpo
	queryset = Tenpo.objects.all()
	template_name = 'tenpo/tenpo.html'

class RirekiListView(ListView):
	model = Rireki
	queryset = Rireki.objects.all()
	template_name = 'tenpo/rireki.html'

class FavoriteListView(ListView):
	model = Favorite
	queryset = Favorite.objects.all()
	template_name = 'tenpo/favorite.html'

tenpo/templates/tenpo/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>クソ店舗サイト</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Metamorphous'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/earlyaccess/roundedmplus1c.css'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css'>
    </head>
  <body>
    <div class='container'>
      <a href="{% url 'tenpo:index' %}"><h1>Title</h1></a>
      <ul class="nav nav-tabs">
        <li class="nav-item">
        <a class="nav-item nav-link" href="{% url 'tenpo:index' %}">トップ</a>
        </li>
        <li class="nav-item">
        <a class="nav-item nav-link" href="{% url 'tenpo:tenpo' %}">店舗</a>
        </li>
        <li class="nav-item">
        <a class="nav-item nav-link" href="{% url 'tenpo:rireki' %}">履歴</a>
        </li>
        <li class="nav-item">
        <a class="nav-item nav-link" href="{% url 'tenpo:favorite' %}">お気に入り</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-item nav-link" href="{% url 'account:logout' %}">ログアウト</a>
        </li>
        <li class="nav-item">
        {% else %}
          <a class="nav-item nav-link" href="{% url 'account:create' %}">ユーザ登録</a>
        </li>
        <li class="nav-item">
          <a class="nav-item nav-link" href="{% url 'account:login' %}">ログイン</a>
        </li>
        {% endif %}
      </ul>
      {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

tenpo/templates/tenpo/favorite.html
{% extends 'tenpo/base.html' %}

{% block content %}
	<div class='container'>
		<div class="card-group">
			{% for tenpo in object_list %}
				<div class="col-sm-12">
					<div class="card border-primary rounded mb-3">
						<div class="card-header border-primary">
							<p class="card-text">登録者：{{ tenpo.favorite_user.username }}</p>
						</div>
						<div class="card-body border-primary">
							<p class="card-text">店舗名：{{ tenpo.favorite_tenpo.tenpo_name }}</p>
							<p class="card-text">カテゴリ：{{ tenpo.favorite_tenpo.tenpo_genre }}</p>
							<p class="card-text">住所：{{ tenpo.favorite_tenpo.tenpo_address }}</p>
							<p class="card-text">電話番号：{{ tenpo.favorite_tenpo.tenpo_phone_number }}</p>
							<p class="card-text">PR文：{{ tenpo.favorite_tenpo.tenpo_pr_message }}</p>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

tenpo/templates/tenpo/index.html
{% extends 'tenpo/base.html' %}

{% block content %}
クソ店舗アプリのページです
{% endblock %}

tenpo/templates/tenpo/rireki.html
{% extends 'tenpo/base.html' %}

{% block content %}
  <div class='container'>
    <div class="card-group">
      {% for tenpo in object_list %}
        <div class="col-sm-12">
          <div class="card border-primary rounded mb-3">
            <div class="card-header border-primary">
              <p class="card-text">閲覧者：{{ tenpo.rireki_user.username }}</p>
            </div>
            <div class="card-body border-primary">
              <p class="card-text">店舗名：{{ tenpo.rireki_tenpo.tenpo_name }}</p>
              <p class="card-text">カテゴリ：{{ tenpo.rireki_tenpo.tenpo_genre }}</p>
              <p class="card-text">住所：{{ tenpo.rireki_tenpo.tenpo_address }}</p>
              <p class="card-text">電話番号：{{ tenpo.rireki_tenpo.tenpo_phone_number }}</p>
              <p class="card-text">PR文：{{ tenpo.rireki_tenpo.tenpo_pr_message }}</p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

tenpo/templates/tenpo/tenpo.html
{% extends 'tenpo/base.html' %}

{% block content %}
  <div class='container'>
    <div class="card-group">
      {% for tenpo in object_list %}
        <div class="col-sm-12">
          <div class="card border-primary rounded mb-3">
            <div class="card-header border-primary">
              <p class="card-text">店舗名：{{ tenpo.tenpo_name }}</p>
            </div>
            <div class="card-body border-primary">
              <p class="card-text">カテゴリ：{{ tenpo.tenpo_genre }}</p>
              <p class="card-text">住所：{{ tenpo.tenpo_address }}</p>
              <p class="card-text">電話番号：{{ tenpo.tenpo_phone_number }}</p>
              <p class="card-text">PR文：{{ tenpo.tenpo_pr_message }}</p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}